baseURL = "https://naccoblog.firebaseapp.com/"
languageCode = "ja"
title = "なっころぐ。"
# add theme 
theme = "minimo"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

disqusShortname = ""
googleAnalytics = "UA-126305998-1"

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "ja"

##### theme minimo params #####

[params.info]
description = "Naccoの技術ブログですん"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "/images/gopher.png" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Nacco"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#7058a3"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "climbing_nacco" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
github = "nacco-bron"
twitter = "climbing_nacco"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "" # "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
#client = "" # algolia / fuse / lunr

[params.search.algolia]
#appId = ""
#indexName = ""
#searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
  post = "/:year/:month/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
 
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[menu.main]]
    name = "Repo"
    weight = 3
    identifier = "repository"
    url = "https://github.com/nacco-bron/naccoblog"
 
[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.ja]
lang = "ja"
languageName = "Japanese"
weight = 1

[languages.en]
lang = "en"
languageName = "English"
weight = 2