version: 2
jobs:
  build:
    docker:
      - image: naccobron/hugo-for-firebase:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: hugo
          name: "Run Hugo"
      - deploy:
          branch: master
          command: firebase deploy --token "$FIREBASE_TOKEN"